// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQDqHSCa4dtM1EGsx0EWkj_5MzJwC4xrc',
    appId: '1:90543510729:android:1593910cc6341f62a76918',
    messagingSenderId: '90543510729',
    projectId: 'fourtitudeassessment',
    storageBucket: 'fourtitudeassessment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwLpDYOeB1hzWlHHORjsAkzZnC-d67y0',
    appId: '1:90543510729:ios:a664ecc2a4ee1b4aa76918',
    messagingSenderId: '90543510729',
    projectId: 'fourtitudeassessment',
    storageBucket: 'fourtitudeassessment.firebasestorage.app',
    iosClientId: '90543510729-j0mddur3kpoeqa0fqeghaj3gql4500ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.neoaiAssessment',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFaOxxqHv8HBzNC5Xir0GsOCeGHXyxK8',
    appId: '1:90543510729:web:e46cbc95e1381d4fa76918',
    messagingSenderId: '90543510729',
    projectId: 'fourtitudeassessment',
    authDomain: 'fourtitudeassessment.firebaseapp.com',
    storageBucket: 'fourtitudeassessment.firebasestorage.app',
    measurementId: 'G-BY5SFL1V0H',
  );

}